In [2]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
env = gym.make('FrozenLake-v0')

In [21]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
alpha = .8
y = .95
num_episodes = 4000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + alpha*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [22]:
print("Reward: " +  str(sum(rList)/num_episodes))

Reward: 0.5255


In [23]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[1.13682028e-01 8.35376863e-03 7.03668944e-03 8.40394050e-03]
 [4.55954881e-03 4.17135830e-03 4.60456745e-03 1.62926506e-01]
 [9.97782645e-02 1.28563942e-03 2.20165659e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.96676976e-03 9.49573322e-03]
 [3.95687756e-01 8.30453457e-04 3.30855505e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.03238019e-04 3.65963789e-06 1.19418641e-04 7.51683094e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.75523797e-03 0.00000000e+00 6.86983483e-01]
 [3.64657051e-03 2.87165237e-01 0.00000000e+00 0.00000000e+00]
 [7.82925788e-01 1.51870615e-04 4.27729922e-05 3.64602130e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.88362704e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.96873604e-01]
 [0.00000000e+00 0.00000000e+00 0.